version: '3.1'

services:
    db:
        image: postgres:10.12
        environment:
            POSTGRES_PASSWORD: "secret"
            POSTGRES_DB: "api"
        ports:
            - "5432:5432"
        networks:
            - postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: unless-stopped

    redis:
        image: redis:5.0.9
        ports:
            - "6379:6379"
        networks:
            - postgres
        restart: unless-stopped

networks:
    postgres:
        driver: bridge
volumes:
    pgdata:
