version: '3.1'

services:
    postgres:
        image: postgres:10.12
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: "secret"
            POSTGRES_DB: "api"
        ports:
            - "5432:5432"
        networks:
            - postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: unless-stopped
    redis:
        image: redis:5.0.9
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - postgres
        restart: unless-stopped
    app:
        container_name: app
        restart: always
        build: .
        env_file:
          - .env
        environment:
            - START_SERVER=true
        ports:
            - "3000:3000"
        networks:
            - postgres
    worker-rss:
        container_name: worker-rss
        restart: always
        build: .
        environment:
            - START_RSS_WORKER=true
        env_file:
            - .env
        networks:
            - postgres
    worker-publish:
        container_name: worker-publish
        restart: always
        build: .
        environment:
            - START_PUBLISH_WORKER=true
        env_file:
            - .env
        networks:
            - postgres

networks:
    postgres:
        driver: bridge
volumes:
    pgdata:
